# Site
# blog's title
title: HexadecimalTeach - 十六進位技術共筆部落格

# subtitle in the banner header
subtitle: HexadecimalTeach - 十六進位技術共筆部落格

# introduction  in the banner header
subtitle_desc: 日常學習與興趣交流

# seo keyword
keywords: 六角學院, 前端, 前端開發, react, vue, angular, node.js, javascript

# blog description（for seo）
description: 由一群六角學生的日常學習與興趣交流的共筆部落格

# self introduction
introduction: 不思量，自難忘！

# your blog favicon icon, support two ways: local and online. the local way need you to put the icon under  themes/hexo-theme-skapp/source/img directory
favicon_ico: ./img/favicon.ico

# blog logo icon in the upper left corner. support the local way and online way. 
logo: ./img/logo.png

# avatar
# avatar: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png
# qrcode: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png

# page default cover
default_cover: http://oo12ugek5.bkt.clouddn.com/images/default_cover.png

# header background picture
header_cover: http://oo12ugek5.bkt.clouddn.com/blog/images/banner-bg.jpg

# 404 page background picture
error_page_bg: http://oo12ugek5.bkt.clouddn.com/blog/images/dogs.jpg

# page loading icon
loader_img: http://oo12ugek5.bkt.clouddn.com/blog/images/loader.gif

# author information
author:
  name: minfive
  link: https://github.com/Mrminfive

# footer information
about:
  info: 本站是由一群六角學生所組成的技術共筆部落格，主要用於分享日常學習及工作的一些心得總結，歡迎點擊右下角訂閱 rss。
#  address: Guangzhou, Guangdong Province, China
#  email: chenxiaowu1994@outlook.com